spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://192.168.80.130:3306/mall_ums
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-member


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
server:
  port: 8000

