spring:
  cloud:
    gateway:
      routes:
#        - id: bd_route
#          uri: http://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://qq.com
#          predicates:
#            - Query=url,qq
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/third/party/**
          filters:
            - RewritePath=/api/third/party/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
server:
  port: 88


# filter 做过滤，将url重写 (什么 重写为 什么)  前提是nacos配置中心要有当前模块[product
# http://localhost:88/api/product/category/list/tree ---->  http://localhost:10001/product/category/list/tree